# -*- coding: utf-8 -*-
"""medical Report dl 05-06-2026.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ttv69rveDOwAoqA7LAUkBGPDfFmxqenD
"""

from google.colab import drive
import numpy as np
import pandas as pd
drive.mount('/content/drive')
path= 'mtsamples.csv'
df=pd.read_csv(path)
df.head()

"""### 1. Number of Reports"""

num_reports = len(df)
print(f"Total number of medical reports: {num_reports}")

"""### 2. Specialty Distribution"""

specialty_distribution = df['medical_specialty'].value_counts()
print("Medical Specialty Distribution:")
print(specialty_distribution)

"""### 3. Most Common Medical Terms

To find the most common medical terms, we'll perform the following steps:
1. Combine the 'description' and 'transcription' columns into a single text body.
2. Clean the text by removing punctuation, numbers, and converting to lowercase.
3. Tokenize the text into individual words.
4. Remove common English stopwords.
5. Count the frequency of each word.
6. Display the most common words.
"""

# Install NLTK if not already installed
#pip install nltk
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import re

# Download necessary NLTK data
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('punkt_tab')

# Combine relevant text columns, handling potential NaNs
df['full_text'] = df['description'].fillna('') + ' ' + df['transcription'].fillna('')

# Function to clean text
def clean_text(text):
    text = text.lower() # Convert to lowercase
    text = re.sub(r'[^a-z\s]', '', text) # Remove punctuation and numbers
    return text

# Apply cleaning to the full_text column
df['cleaned_text'] = df['full_text'].apply(clean_text)

# Tokenize and remove stopwords
stop_words = set(stopwords.words('english'))

def tokenize_and_filter(text):
    words = word_tokenize(text)
    filtered_words = [word for word in words if word not in stop_words and len(word) > 2] # Remove short words too
    return filtered_words

df['tokens'] = df['cleaned_text'].apply(tokenize_and_filter)

# Flatten the list of tokens and count word frequencies
all_words = [word for sublist in df['tokens'] for word in sublist]

from collections import Counter
word_counts = Counter(all_words)

print("\nMost Common Medical Terms:")
for word, count in word_counts.most_common(20):
    print(f"{word}: {count}")

"""### Medical Term Dictionary with Frequency

Based on the analysis of the combined 'description' and 'transcription' columns, here is a dictionary of the most common medical terms and their frequencies, after cleaning and removing stopwords.
"""

# The 'word_counts' variable already contains the frequency of each word
# We can convert it to a dictionary if preferred, or just display its contents
medical_term_dictionary = dict(word_counts)

# Display the top 20 terms from the dictionary for brevity, or you can print the full dictionary
print("Top 20 Medical Terms and their Frequencies:")
for term, freq in word_counts.most_common(20):
    print(f"{term}: {freq}")

# To see the full dictionary (it can be very large):
# display(medical_term_dictionary)

"""### Task 3: Baseline Model

To create a baseline model for classifying medical specialties, we'll follow these steps:
1.  **Data Preprocessing**: Prepare the 'medical_specialty' as the target variable by encoding it numerically and split the dataset.
2.  **Text Embedding**: Convert the cleaned medical text into numerical features using TF-IDF (Term Frequency-Inverse Document Frequency).
3.  **Model Definition**: Build a simple neural network using Keras/TensorFlow with dense layers for classification.
4.  **Model Training**: Train the model on the preprocessed data.
5.  **Model Evaluation**: Evaluate the model's performance.

#### 1. Data Preprocessing
"""

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

# Drop rows where 'medical_specialty' is missing
df_model = df.dropna(subset=['medical_specialty']).copy()

# Encode the target variable 'medical_specialty'
label_encoder = LabelEncoder()
df_model['specialty_encoded'] = label_encoder.fit_transform(df_model['medical_specialty'])

# Define features (X) and target (y)
X = df_model['cleaned_text'] # Using the cleaned text generated in Task 1
y = df_model['specialty_encoded']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

print(f"Training set size: {X_train.shape[0]} samples")
print(f"Test set size: {X_test.shape[0]} samples")
print(f"Number of unique medical specialties: {len(label_encoder.classes_)}")

"""#### 2. Text Embedding (TF-IDF Vectorization)"""

from sklearn.feature_extraction.text import TfidfVectorizer

# Initialize TF-IDF Vectorizer
# max_features can be adjusted to control the vocabulary size
tfidf_vectorizer = TfidfVectorizer(max_features=5000)

# Fit the vectorizer on the training data and transform both training and test data
X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)
X_test_tfidf = tfidf_vectorizer.transform(X_test)

print(f"Shape of X_train_tfidf: {X_train_tfidf.shape}")
print(f"Shape of X_test_tfidf: {X_test_tfidf.shape}")

"""#### 3. Model Definition (Dense Neural Network)"""

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.optimizers import Adam

# Get the number of features (vocabulary size) from TF-IDF output
input_dim = X_train_tfidf.shape[1]
# Get the number of output classes (unique medical specialties)
num_classes = len(label_encoder.classes_)

# Define the model architecture
model = Sequential([
    Dense(256, input_dim=input_dim, activation='relu'),
    Dropout(0.5),
    Dense(128, activation='relu'),
    Dropout(0.5),
    Dense(num_classes, activation='softmax') # Softmax for multi-class classification
])

# Compile the model
model.compile(loss='sparse_categorical_crossentropy',
              optimizer=Adam(learning_rate=0.001),
              metrics=['accuracy'])

model.summary()

"""#### 4. Model Training"""

# Convert sparse matrices to dense arrays for Keras if necessary (Dense layers usually require dense input)
X_train_dense = X_train_tfidf.toarray()
X_test_dense = X_test_tfidf.toarray()

history = model.fit(X_train_dense, y_train,
                    epochs=10,
                    batch_size=32,
                    validation_split=0.1,
                    verbose=1)

"""#### 5. Model Evaluation"""

from sklearn.metrics import classification_report, accuracy_score
import numpy as np

# Evaluate the model on the test set
loss, accuracy = model.evaluate(X_test_dense, y_test, verbose=0)
print(f"Test Loss: {loss:.4f}")
print(f"Test Accuracy: {accuracy:.4f}")

# Predict the probabilities for the test set
y_pred_probs = model.predict(X_test_dense)
# Get the predicted classes (the class with the highest probability)
y_pred = np.argmax(y_pred_probs, axis=1)

# Print classification report
print("\nClassification Report:")
print(classification_report(y_test, y_pred, target_names=label_encoder.classes_, zero_division=0))

"""### Task 4: Self-Attention Model

To build a self-attention model as requested, we'll follow these steps:
1.  **Text Tokenization and Padding**: Prepare the `cleaned_text` by converting it into sequences of integers and padding them to a uniform length suitable for an embedding layer.
2.  **Model Definition**: Construct a Keras model using `tf.keras.layers.Embedding`, `tf.keras.layers.MultiHeadAttention`, and `tf.keras.layers.Dense` for the output.
3.  **Model Training**: Train the self-attention model on the preprocessed data.
4.  **Model Evaluation**: Evaluate the model's performance on the test set.

#### 1. Text Tokenization and Padding for Embedding Layer
"""

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

# Define vocabulary size and maximum sequence length
VOCAB_SIZE = 10000  # Limiting vocabulary to top 10,000 words
MAX_LEN = 200       # Maximum length of text sequences after padding

# Initialize and fit tokenizer on training data
tokenizer = Tokenizer(num_words=VOCAB_SIZE, oov_token="<unk>")
tokenizer.fit_on_texts(X_train)

# Convert text to sequences of integers
X_train_sequences = tokenizer.texts_to_sequences(X_train)
X_test_sequences = tokenizer.texts_to_sequences(X_test)

# Pad sequences to ensure uniform length
X_train_padded = pad_sequences(X_train_sequences, maxlen=MAX_LEN, padding='post', truncating='post')
X_test_padded = pad_sequences(X_test_sequences, maxlen=MAX_LEN, padding='post', truncating='post')

# Actual vocabulary size including padding token (0)
vocab_size_actual = len(tokenizer.word_index) + 1

print(f"Shape of X_train_padded: {X_train_padded.shape}")
print(f"Shape of X_test_padded: {X_test_padded.shape}")
print(f"Actual vocabulary size: {vocab_size_actual}")

"""#### 2. Model Definition (Self-Attention Model)"""

import tensorflow as tf
from tensorflow.keras.layers import Embedding, GlobalAveragePooling1D, MultiHeadAttention, Dense, Dropout
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam

EMBEDDING_DIM = 128  # Dimension of the word embeddings
NUM_HEADS = 2        # Number of attention heads
KEY_DIM = EMBEDDING_DIM # Dimension of each attention head's key/query/value

# Input Layer
text_input = tf.keras.Input(shape=(MAX_LEN,), name='text_input')

# Embedding Layer
embedded_sequences = Embedding(
    input_dim=vocab_size_actual,
    output_dim=EMBEDDING_DIM,
    input_length=MAX_LEN,
    name='embedding_layer'
)(text_input)

# MultiHeadAttention Layer (Self-Attention)
# For self-attention, query, key, and value are all the same input sequence.
attention_output = MultiHeadAttention(
    num_heads=NUM_HEADS,
    key_dim=KEY_DIM,
    name='multi_head_attention'
)(embedded_sequences, embedded_sequences)

# Global Average Pooling to reduce sequence dimension for the Dense layer
pooled_output = GlobalAveragePooling1D(name='global_average_pooling')(attention_output)

# Output Layer for classification
classification_output = Dense(
    units=num_classes, # `num_classes` is from Task 3, representing unique medical specialties
    activation='softmax',
    name='output_layer'
)(pooled_output)

# Create the Model
model_attention = Model(inputs=text_input, outputs=classification_output)

# Compile the model
model_attention.compile(
    optimizer=Adam(learning_rate=0.001),
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

model_attention.summary()

"""#### 3. Model Training"""

history_attention = model_attention.fit(
    X_train_padded, y_train,
    epochs=10,
    batch_size=32,
    validation_split=0.1,
    verbose=1
)

"""#### 4. Model Evaluation"""

from sklearn.metrics import classification_report
import numpy as np

# Evaluate the model on the test set
loss_attention, accuracy_attention = model_attention.evaluate(X_test_padded, y_test, verbose=0)
print(f"Test Loss (Self-Attention): {loss_attention:.4f}")
print(f"Test Accuracy (Self-Attention): {accuracy_attention:.4f}")

# Predict the probabilities for the test set
y_pred_probs_attention = model_attention.predict(X_test_padded)
# Get the predicted classes
y_pred_attention = np.argmax(y_pred_probs_attention, axis=1)

# Print classification report
print("\nClassification Report (Self-Attention Model):")
print(classification_report(y_test, y_pred_attention, target_names=label_encoder.classes_, zero_division=0))

"""### Task 5: Positional Encoding

Positional encoding is a technique used in transformer models to inject information about the relative or absolute position of the tokens in the sequence. Since the transformer architecture does not inherently process the sequence in order (unlike RNNs), positional encodings are added to the input embeddings to provide this crucial positional information. We'll implement this from scratch and visualize it.
"""

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

def get_angles(pos, i, d_model):
    angle_rates = 1 / np.power(10000, (2 * (i//2)) / np.float32(d_model))
    return pos * angle_rates

def positional_encoding(position, d_model):
    angle_rads = get_angles(np.arange(position)[:, np.newaxis],
                            np.arange(d_model)[np.newaxis, :],
                            d_model)

    # apply sin to even indices in the array; 2i
    angle_rads[:, 0::2] = np.sin(angle_rads[:, 0::2])

    # apply cos to odd indices in the array; 2i+1
    angle_rads[:, 1::2] = np.cos(angle_rads[:, 1::2])

    pos_encoding = angle_rads[np.newaxis, ...]
    return tf.cast(pos_encoding, dtype=tf.float32)

print(f"Positional Encoding function defined for MAX_LEN={MAX_LEN} and EMBEDDING_DIM={EMBEDDING_DIM}.")

# Generate positional encodings for visualization
# Using MAX_LEN for position and EMBEDDING_DIM for d_model from the self-attention model setup

pe = positional_encoding(MAX_LEN, EMBEDDING_DIM)

# Squeeze the first dimension (batch dimension, which is 1) for plotting
pe_squeezed = pe[0, :, :].numpy()

plt.figure(figsize=(15, 8))
sns.heatmap(pe_squeezed, cmap='viridis')
plt.xlabel('Token Position (Embedding Dimension Index)')
plt.ylabel('Sentence Position')
plt.title('Positional Encoding Visualization (MAX_LEN x EMBEDDING_DIM)')
plt.show()

"""#### 3. Model Definition (Dense Neural Network)"""

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.optimizers import Adam

input_dim = X_train_tfidf.shape[1]
num_classes = len(label_encoder.classes_)

model = Sequential([
    Dense(256, input_dim=input_dim, activation='relu'),
    Dropout(0.5),
    Dense(128, activation='relu'),
    Dropout(0.5),
    Dense(num_classes, activation='softmax') # Softmax for multi-class classification
])

model.compile(loss='sparse_categorical_crossentropy',
              optimizer=Adam(learning_rate=0.001),
              metrics=['accuracy'])

model.summary()

"""#### 4. Model Training"""

# Convert sparse matrices to dense arrays for Keras if necessary (Dense layers usually require dense input)
X_train_dense = X_train_tfidf.toarray()
X_test_dense = X_test_tfidf.toarray()

history = model.fit(X_train_dense, y_train,
                    epochs=10,
                    batch_size=32,
                    validation_split=0.1,
                    verbose=1)

"""#### 5. Model Evaluation"""

from sklearn.metrics import classification_report, accuracy_score
import numpy as np
loss, accuracy = model.evaluate(X_test_dense, y_test, verbose=0)
print(f"Test Loss: {loss:.4f}")
print(f"Test Accuracy: {accuracy:.4f}")

# Predict the probabilities for the test set
y_pred_probs = model.predict(X_test_dense)
# Get the predicted classes (the class with the highest probability)
y_pred = np.argmax(y_pred_probs, axis=1)

# Print classification report
print("\nClassification Report:")
print(classification_report(y_test, y_pred, target_names=label_encoder.classes_, zero_division=0))

"""### Task 6: Diagnostic Importance Analysis

To identify which words influence the prediction of a medical specialty, we can examine the weights of the output layer in our trained baseline model. For each specialty, words with higher positive weights contribute more to the model's decision to classify a report into that specialty.
"""

import pandas as pd
import numpy as np

# Get weights from each Dense layer
# model.layers[0] is the first Dense layer (input_dim=5000, output_dim=256)
w1 = model.layers[0].get_weights()[0] # Shape (5000, 256)

# model.layers[2] is the second Dense layer (input_dim=256, output_dim=128)
w2 = model.layers[2].get_weights()[0] # Shape (256, 128)

# model.layers[4] is the third/output Dense layer (input_dim=128, output_dim=40)
w3 = model.layers[4].get_weights()[0] # Shape (128, 40)

# Calculate effective weights from input features to output classes
# This is a linear approximation and ignores non-linear activations and dropout,
# but provides a simple way to interpret feature importance across layers.
effective_weights = np.dot(np.dot(w1, w2), w3) # Resulting shape (5000, 40)

# Get the feature names (words) from the TF-IDF vectorizer
feature_names = tfidf_vectorizer.get_feature_names_out()

# Create a DataFrame to store word importance for each class
word_importance_df = pd.DataFrame(effective_weights, index=feature_names, columns=label_encoder.classes_)

print("Top 10 most influential words for each medical specialty:")
print("----------------------------------------------------------")

# Display the top N words for each medical specialty
num_top_words = 10
for specialty in label_encoder.classes_:
    top_words = word_importance_df[specialty].nlargest(num_top_words)
    print(f"\nSpecialty: {specialty}")
    for word, importance in top_words.items():
        print(f"  - {word}: {importance:.4f}")

"""### Save Models

Saving the trained models allows them to be reused later without needing to retrain them. We will save both the baseline model and the self-attention model.
"""

import os

# Create a directory to save models if it doesn't exist
model_save_dir = 'saved_models'
if not os.path.exists(model_save_dir):
    os.makedirs(model_save_dir)

# Save the baseline model
baseline_model_path = os.path.join(model_save_dir, 'baseline_model.keras')
model.save(baseline_model_path)
print(f"Baseline model saved to {baseline_model_path}")
# Save the self-attention model
attention_model_path = os.path.join(model_save_dir, 'self_attention_model.keras')
model_attention.save(attention_model_path)
print(f"Self-attention model saved to {attention_model_path}")

"""### Display Model Accuracy

Now that the models are saved, let's display their final accuracies on the test set for a quick overview.
"""

import tensorflow as tf
import os
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_extraction.text import TfidfVectorizer
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
import re
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

# --- Check and load models if not already in memory ---

if 'model' not in locals():
    baseline_model_path = os.path.join('saved_models', 'baseline_model.keras')
    try:
        model = tf.keras.models.load_model(baseline_model_path)
        print(f"Baseline model loaded from {baseline_model_path}")
    except Exception as e:
        print(f"Error loading baseline model: {e}")
        print("Please ensure the 'save all models' cell was run successfully.")

if 'model_attention' not in locals():
    attention_model_path = os.path.join('saved_models', 'self_attention_model.keras')
    try:
        model_attention = tf.keras.models.load_model(attention_model_path)
        print(f"Self-attention model loaded from {attention_model_path}")
    except Exception as e:
        print(f"Error loading self-attention model: {e}")
        print("Please ensure the 'save all models' cell was run successfully.")

# --- Check and re-create data variables if necessary ---

# Check if core data variables for evaluation are missing
if ('y_test' not in locals() or
    'X_test_dense' not in locals() or
    'X_test_padded' not in locals()):

    print("Detected missing data variables (y_test, X_test_dense, X_test_padded). Re-running data preprocessing steps...")

    # Re-load df if not available
    if 'df' not in locals():
        print("  Loading dataframe from /content/drive/My Drive/mtsamples.csv...")
        path = '/content/drive/My Drive/mtsamples.csv'
        # Ensure drive is mounted, or add a check/mount call here if not guaranteed
        try:
            df = pd.read_csv(path)
            print("  Dataframe loaded.")
        except Exception as e:
            print(f"  Error loading dataframe: {e}. Please ensure Google Drive is mounted and 'mtsamples.csv' is at the specified path.")
            # Exit or raise error if df cannot be loaded
            raise

    # Re-create cleaned_text (from cell 6421f3cb dependencies)
    if 'cleaned_text' not in df.columns:
        print("  Cleaning text...")
        nltk.download('punkt', quiet=True)
        nltk.download('stopwords', quiet=True)
        # nltk.download('punkt_tab', quiet=True) # If this was a necessary download, keep it
        stop_words = set(stopwords.words('english'))

        def _clean_text_func(text):
            text = str(text).lower() # Ensure text is string and lowercase
            text = re.sub(r'[^a-z\s]', '', text) # Remove punctuation and numbers
            return text

        df['full_text'] = df['description'].fillna('') + ' ' + df['transcription'].fillna('')
        df['cleaned_text'] = df['full_text'].apply(_clean_text_func)
        print("  Text cleaned.")

    # Re-encode target and split data (from cell f2f8e0ec)
    if 'X_test' not in locals() or 'y_test' not in locals():
        print("  Splitting data into training and test sets...")
        df_model = df.dropna(subset=['medical_specialty']).copy()
        label_encoder = LabelEncoder()
        df_model['specialty_encoded'] = label_encoder.fit_transform(df_model['medical_specialty'])
        X = df_model['cleaned_text']
        y = df_model['specialty_encoded']
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)
        num_classes = len(label_encoder.classes_) # Also define num_classes if needed
        print("  Data split.")

    # Re-create TF-IDF features (from cell fdfceedf and d9dc1e3c)
    if 'X_test_dense' not in locals():
        print("  Creating TF-IDF features for baseline model...")
        tfidf_vectorizer = TfidfVectorizer(max_features=5000)
        # Fit and transform on X_train first to ensure consistency
        X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)
        X_test_tfidf = tfidf_vectorizer.transform(X_test)
        X_test_dense = X_test_tfidf.toarray()
        print("  TF-IDF features created.")

    # Re-create padded sequences (from cell 11dab537)
    if 'X_test_padded' not in locals():
        print("  Creating padded sequences for self-attention model...")
        VOCAB_SIZE = 10000
        MAX_LEN = 200 # Define MAX_LEN as it's used by model_attention
        tokenizer = Tokenizer(num_words=VOCAB_SIZE, oov_token="<unk>")
        tokenizer.fit_on_texts(X_train)
        X_test_sequences = tokenizer.texts_to_sequences(X_test)
        X_test_padded = pad_sequences(X_test_sequences, maxlen=MAX_LEN, padding='post', truncating='post')
        print("  Padded sequences created.")

    print("Data variables are now available.")

# --- Evaluate the models on the test set ---
if 'model' in locals():
    loss_baseline, accuracy_baseline = model.evaluate(X_test_dense, y_test, verbose=0)
    print(f"Baseline Model - Test Loss: {loss_baseline:.4f}")
    print(f"Baseline Model - Test Accuracy: {accuracy_baseline:.4f}")
else:
    print("Baseline model not loaded; cannot evaluate.")

if 'model_attention' in locals():
    loss_attention, accuracy_attention = model_attention.evaluate(X_test_padded, y_test, verbose=0)
    print(f"Self-Attention Model - Test Loss: {loss_attention:.4f}")
    print(f"Self-Attention Model - Test Accuracy: {accuracy_attention:.4f}")
else:
    print("Self-Attention model not loaded; cannot evaluate.")